### ISSUE TITLE
Balancing

### ISSUE THREAD

**Issue by tytower** [JohnMacrae/ESP32-Battery-Protection-System#10]
Quote" using good cells that are top balanced on installation, little if any subsequent balancing should be necessary."

A pretty broad statement and largely false. 
In use I find I need to top balance my cells about every 6 months to ensure no one cell gets up near the 3.65 v limit. They naturally seem to do this when left on their own.

I charge 8 cells to 54 volts only and still this imbalance happens regularly . I have 8 batteries at different locations predominantly 50 ah cells but one 100 Ah battery for home use.

I always run a BMS and active balancer . The paralleling of cells first and then series them is dangerous in that if one cell shorts and goes flat it will pull the co joined cells down with it and force damage on them so thats a bad practice. Series all the cells first then parallel the strings with a BMS on every string . 

I have been going 3 years and have not lost a cell yet. Can you say the same?

**Comment by JohnMacrae** [comment]
Thanks for your feedback - Absolutely nothing to do with the project of course. 

I can't say the same as you - I've been going way longer without degradation or loss. 

Therefore not an issue with this project.  YMMV.

**Comment by tytower** [comment]
MM well that was a rtart . I came looking for an MPPT code file that actually turned the battery off for a full second before reading its voltage . If the charger is left on then the program just reads the charging voltage and all that I have seen do that . Does this one ?
